apiVersion: v1
kind: Service
metadata:
  name: terminus-exporter-svc
  namespace: terminus
  labels:
    app: terminus-enforcer
spec:
  type: ClusterIP
  selector:
    app: terminus-exporter
  ports:
    - name: metrics-port
      port: 9201
      targetPort: 9201
      protocol: TCP